name: 'Prepare Kubernetes Deployment Action'
description: 'Action used to prepare the files necessary for a Kubernetes deployment'
inputs:
  SERVICE_NAME:
    description: 'The name of the service to deploy'
    required: true
  SERVICE_REPLICA_COUNT:
    description: 'The number of replicas of the service to deploy'
    required: true
  SERVICE_IMAGE_NAME:
    description: 'The name of the image to deploy'
    required: true
  SERVICE_IMAGE_NAMESPACE:
    description: 'The namespace of the image to deploy'
    required: true
  SERVICE_IMAGE_VERSION:
    description: 'The version of the image to deploy'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.SERVICE_NAME }}
    - ${{ inputs.SERVICE_REPLICA_COUNT }}
    - ${{ inputs.SERVICE_IMAGE_NAME }}
    - ${{ inputs.SERVICE_IMAGE_NAMESPACE }}
    - ${{ inputs.SERVICE_IMAGE_VERSION }}
